openapi: 3.2.0
info:
  title: Kickstart Available Features Controller API
  description: API documentation for Kickstart services
  contact:
    name: Your Team
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
servers:
- url: https://platform.digitalremedy.com
  description: Generated server url
tags:
- name: available-features-controller
paths:
  /api/features:
    get:
      tags:
      - available-features-controller
      operationId: getAvailableFeatures
      responses:
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
