openapi: 3.2.0
info:
  title: Kickstart Sign Up Controller API
  description: API documentation for Kickstart services
  contact:
    name: Your Team
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
servers:
- url: https://platform.digitalremedy.com
  description: Generated server url
tags:
- name: sign-up-controller
paths:
  /api/sendVerificationEmail:
    post:
      tags:
      - sign-up-controller
      operationId: sendVerificationEmail
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: app
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: object
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
